### ISSUE TITLE
Incompatibility with pretalx 2023.1.0

### ISSUE THREAD

**Issue by lorenzleutgeb** [pretalx/pretalx-public-voting#31]
The line https://github.com/pretalx/pretalx-public-voting/blob/17deaabe2f1378d9c8c3c06b2081bf8bfadf477a/pretalx_public_voting/templates/pretalx_public_voting/settings.html#L10 seems to be incompatible with pretalx 2023.1.0.

In pretalx 2.3.2 there is a file [`src/pretalx/static/vendored/moment-timezone-with-data-2012-2022.js`](https://github.com/pretalx/pretalx/blob/v2.3.2/src/pretalx/static/vendored/moment-timezone-with-data-2012-2022.js) while in pretalx 2023.1.0 I could only find [`src/pretalx/static/vendored/moment-timezone-with-data-10-year-range.js`](https://github.com/pretalx/pretalx/blob/v2023.1.0/src/pretalx/static/vendored/moment-timezone-with-data-10-year-range.js).

The stack trace that I get is:

```
Traceback (most recent call last):
  File "/nix/store/.../Django-4.2.4/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/nix/store/.../Django-4.2.4/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/nix/store/.../Django-4.2.4/lib/python3.10/site-packages/django/template/response.py", line 114, in render                      [F2] Menu - CPython 3.10.12
    self.content = self.rendered_content
  File "/nix/store/.../Django-4.2.4/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/nix/store/.../Django-4.2.4/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/nix/store/.../Django-4.2.4/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/nix/store/.../Django-4.2.4/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/nix/store/.../Django-4.2.4/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/nix/store/.../Django-4.2.4/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/nix/store/.../Django-4.2.4/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/nix/store/.../Django-4.2.4/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/nix/store/.../Django-4.2.4/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/nix/store/.../Django-4.2.4/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/nix/store/.../Django-4.2.4/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/nix/store/.../Django-4.2.4/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/nix/store/.../Django-4.2.4/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/nix/store/.../Django-4.2.4/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/nix/store/.../Django-4.2.4/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/nix/store/.../Django-4.2.4/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/nix/store/krknqki04p92w8zjpf631ldaiz9qqfj5-python3.10-django-compressor-4.4/lib/python3.10/site-packages/compressor/templatetags/compress.py", line 160, in render
    return self.render_compressed(
  File "/nix/store/krknqki04p92w8zjpf631ldaiz9qqfj5-python3.10-django-compressor-4.4/lib/python3.10/site-packages/compressor/templatetags/compress.py", line 106, in render_compressed
    return self.render_offline(context)
  File "/nix/store/krknqki04p92w8zjpf631ldaiz9qqfj5-python3.10-django-compressor-4.4/lib/python3.10/site-packages/compressor/templatetags/compress.py", line 71, in render_offline
    original_content = self.get_original_content(context)
  File "/nix/store/krknqki04p92w8zjpf631ldaiz9qqfj5-python3.10-django-compressor-4.4/lib/python3.10/site-packages/compressor/templatetags/compress.py", line 146, in get_original_content
    return self.nodelist.render(context)
  File "/nix/store/.../Django-4.2.4/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/nix/store/.../Django-4.2.4/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/nix/store/.../Django-4.2.4/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/nix/store/.../Django-4.2.4/lib/python3.10/site-packages/django/templatetags/static.py", line 116, in render
    url = self.url(context)
  File "/nix/store/.../Django-4.2.4/lib/python3.10/site-packages/django/templatetags/static.py", line 113, in url
    return self.handle_simple(path)
  File "/nix/store/.../Django-4.2.4/lib/python3.10/site-packages/django/templatetags/static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
  File "/nix/store/.../Django-4.2.4/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
  File "/nix/store/.../Django-4.2.4/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
  File "/nix/store/.../Django-4.2.4/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 513, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for 'vendored/moment-timezone-with-data-2012-2022.js'
```

**Comment by rixx** [comment]
This has already been fixed in the plugin (as you quoted yourself :wink: ), it's just not been released. It's now part of the 1.3.0 release.
